language: ruby
cache: bundler
os: linux
dist: xenial

rvm:
  - 2.5
  - 2.6
  - 2.7
  - ruby-head


before_install:
  - gem install bundler

gemfile:
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile
  - gemfiles/rails_6.1.gemfile
  - gemfiles/mongoid_5.0.gemfile
  - gemfiles/mongoid_6.0.gemfile
  - gemfiles/mongoid_7.0.gemfile
  - gemfiles/mongoid_7.1.gemfile

jobs:
  allow_failures:
    - rvm: ruby-head
  include:
    - rvm: 2.6
      env: RUBYOPT="--enable-frozen-string-literal"
      gemfile: gemfiles/rails_5.2.gemfile

addons:
  code_climate:
    repo_token: b84a33c35c698270ad54261655bc25161a0853386825a2d54fb1c7a11c2b2785
