language: ruby
rvm:
  - 2.3
  - 2.4
  - 2.5

before_install:
  - gem install bundler

gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile

# matrix:
#   exclude:
#     # Rails 5.0 only works with Ruby >= 2.2
#     - rvm: 1.9.3
#       gemfile: gemfiles/rails_5.0.gemfile
#     - rvm: 2.0.0
#       gemfile: gemfiles/rails_5.0.gemfile
#     - rvm: 2.1
#       gemfile: gemfiles/rails_5.0.gemfile
#
addons:
  code_climate:
    repo_token: b84a33c35c698270ad54261655bc25161a0853386825a2d54fb1c7a11c2b2785
